# Generated by Django 6.0.3 on 2026-03-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotaion_time', models.IntegerField()),
                ('open_delay', models.IntegerField()),
                ('servo_angle', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
