# Generated by Django 6.0.3 on 2026-03-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishtray', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastFoodTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_food', models.IntegerField()),
            ],
        ),
    ]
