# Generated by Django 6.0.3 on 2026-03-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishtray', '0002_lastfoodtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastfoodtime',
            name='last_food',
            field=models.DateTimeField(),
        ),
    ]
