# Generated by Django 6.0.3 on 2026-03-27 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishtray', '0003_alter_lastfoodtime_last_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastfoodtime',
            name='last_food',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
